import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { RxDashboard } from "react-icons/rx";
import Sidebar from "@/components/layout/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="xl:flex">
        <div className="xl:w-[20%] xl:shadow-xl"><Sidebar/></div>
        <div className="xl:w-[80%] xl:shadow-xl">  {children}</div></main>
      </body>

    </html>
  );
}
